server:
  port: 8215
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8200/eureka
spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_examples?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      filter-order: 3