server:
  port: 8215
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8200/eureka
spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: cpm.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-examples?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true